FROM golang:1.16-alpine as build

COPY ./ /build
RUN cd /build/services/query/; CGO_ENABLED=1 GOBIN=/bin/ go install ./cmd/query/;

FROM alpine as prod

COPY --from=build /bin/query /bin/query

WORKDIR /query/

CMD ["/bin/query"]
