FROM golang:1.16-alpine as build

COPY ./ /build
RUN cd /build/services/ui/; CGO_ENABLED=1 GOBIN=/bin/ go install ./cmd/ui/;

FROM alpine as prod

COPY --from=build /bin/ui /bin/ui
COPY --from=build /build/services/ui/web /ui/web
WORKDIR /ui/

CMD ["/bin/ui"]
